on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master        
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }} 
            git fetch 
            git checkout ${{ secrets.MAIN_BRANCH }} 
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            exit
      - name: cleanup
        run: rm -rf ~/.ssh
